# Generated by Django 5.0.4 on 2024-05-03 17:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('theatre', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('03742546-6305-4b21-8a31-95d2b2c001be'), editable=False, primary_key=True, serialize=False)),
                ('actor_name', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('movie_name', models.CharField(max_length=255)),
                ('movie_img', models.ImageField(upload_to='uploads/movies')),
                ('movie_description', models.TextField()),
                ('price', models.FloatField()),
                ('showing_date', models.DateField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('rating', models.FloatField()),
                ('showing_due', models.DateField()),
                ('actors', models.ManyToManyField(to='movie.actor')),
                ('categories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='movie.category')),
                ('theatre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_theatre', to='theatre.theatre')),
            ],
        ),
    ]
