# Generated by Django 5.0.4 on 2024-05-06 12:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='id',
            field=models.UUIDField(default=uuid.UUID('4831caf7-73ce-4a8b-9cd8-49c7d2b5d634'), editable=False, primary_key=True, serialize=False),
        ),
    ]
