# Generated by Django 5.0.4 on 2024-05-03 18:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='id',
            field=models.UUIDField(default=uuid.UUID('d52cd9cf-1461-451a-811b-5eca9e3ba29b'), editable=False, primary_key=True, serialize=False),
        ),
    ]
