# Generated by Django 5.0.4 on 2024-05-06 21:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0005_alter_actor_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='id',
            field=models.UUIDField(default=uuid.UUID('45eba0a0-2251-41bc-a88c-28cc17c0770a'), editable=False, primary_key=True, serialize=False),
        ),
    ]
