# Generated by Django 5.0.4 on 2024-05-11 23:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('theatre', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('0a68838c-73da-42bc-83ab-98b921b232be'), editable=False, primary_key=True, serialize=False)),
                ('actor_name', models.CharField(max_length=225)),
                ('actor_img', models.ImageField(blank=True, upload_to='uploads/actors')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('movie_name', models.CharField(max_length=255)),
                ('movie_img', models.ImageField(upload_to='uploads/movies')),
                ('movie_description', models.TextField(blank=True)),
                ('price', models.FloatField()),
                ('showing_date', models.DateField()),
                ('show_time_mins', models.IntegerField()),
                ('rating', models.FloatField()),
                ('showing_due', models.DateField()),
                ('actors', models.ManyToManyField(blank=True, to='movie.actor')),
                ('categories', models.ManyToManyField(to='movie.category')),
                ('theatre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_theatre', to='theatre.theatre')),
            ],
        ),
        migrations.CreateModel(
            name='IPAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=100)),
                ('favorite', models.BooleanField(default=False)),
                ('movieId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fav_ip', to='movie.movie')),
            ],
        ),
    ]
