# Generated by Django 5.0.4 on 2024-05-08 21:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('theatre', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('0f95f2af-dac2-461b-a270-e4c0788f6586'), editable=False, primary_key=True, serialize=False)),
                ('actor_name', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('movie_name', models.CharField(max_length=255)),
                ('movie_img', models.ImageField(upload_to='uploads/movies')),
                ('movie_description', models.TextField(blank=True)),
                ('price', models.FloatField()),
                ('showing_date', models.DateField()),
                ('rating', models.FloatField()),
                ('showing_due', models.DateField()),
                ('favorite', models.BooleanField(default=False)),
                ('actors', models.ManyToManyField(blank=True, to='movie.actor')),
                ('categories', models.ManyToManyField(to='movie.category')),
                ('theatre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_theatre', to='theatre.theatre')),
            ],
        ),
    ]
