# Generated by Django 5.0.4 on 2024-05-08 21:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='id',
            field=models.UUIDField(default=uuid.UUID('986f3a11-ed79-432c-80c5-d86f193295ea'), editable=False, primary_key=True, serialize=False),
        ),
    ]
