# Generated by Django 5.0.4 on 2024-05-10 21:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ipaddress',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='actor',
            name='id',
            field=models.UUIDField(default=uuid.UUID('be0d66dd-dd9c-43a0-8715-cee51d983aa9'), editable=False, primary_key=True, serialize=False),
        ),
    ]
