# Generated by Django 5.0.4 on 2024-05-11 23:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='id',
            field=models.UUIDField(default=uuid.UUID('d1ee17bf-8bbf-4a6a-8ab1-3134b88643f0'), editable=False, primary_key=True, serialize=False),
        ),
    ]
