# Generated by Django 5.0.4 on 2024-05-11 17:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_alter_ipaddress_unique_together_alter_actor_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='id',
            field=models.UUIDField(default=uuid.UUID('0df51a28-b8b1-4ffd-8ca3-2e28ea94da34'), editable=False, primary_key=True, serialize=False),
        ),
    ]
