# Generated by Django 5.0.4 on 2024-05-08 21:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_alter_actor_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='id',
            field=models.UUIDField(default=uuid.UUID('c907552e-af0e-4bce-a00f-00e860bdb47f'), editable=False, primary_key=True, serialize=False),
        ),
    ]
