# Generated by Django 5.0.4 on 2024-05-12 11:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_alter_actor_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='id',
            field=models.UUIDField(default=uuid.UUID('7d5f56ae-a9d0-457c-9f8a-e3ccfb5e7100'), editable=False, primary_key=True, serialize=False),
        ),
    ]
