# Generated by Django 5.0.4 on 2024-05-12 14:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_alter_actor_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='id',
            field=models.UUIDField(default=uuid.UUID('c249ff20-cab5-42d7-9fae-ff60e6b9e20d'), editable=False, primary_key=True, serialize=False),
        ),
    ]
