# Generated by Django 5.0.4 on 2024-05-06 20:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_alter_actor_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='id',
            field=models.UUIDField(default=uuid.UUID('d5189768-236e-4b32-ad07-11aa6c562c84'), editable=False, primary_key=True, serialize=False),
        ),
    ]
