# Generated by Django 5.0.4 on 2024-05-06 21:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_alter_actor_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b1899c09-a53e-4eba-ae35-d0797a6515f9'), editable=False, primary_key=True, serialize=False),
        ),
    ]
