# Generated by Django 5.0.4 on 2024-05-12 21:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_alter_actor_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b478e620-2318-4691-86b8-acbd2b33a31b'), editable=False, primary_key=True, serialize=False),
        ),
    ]
