# Generated by Django 5.0.4 on 2024-05-12 21:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0005_alter_actor_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='id',
            field=models.UUIDField(default=uuid.UUID('d0a26d91-f3df-4e46-83d6-b2fec5ff7e6e'), editable=False, primary_key=True, serialize=False),
        ),
    ]
