# Generated by Django 5.0.4 on 2024-05-11 23:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Theatre',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('theatre_num', models.IntegerField()),
                ('show_time', models.DateTimeField(blank=True)),
                ('is_show', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('seat_num', models.CharField(max_length=225)),
                ('type', models.CharField(choices=[('normal', 'Normal'), ('vip', 'Vip')], default='normal')),
                ('isIdle', models.BooleanField(default=True)),
                ('theatre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='place_theatre', to='theatre.theatre')),
            ],
        ),
    ]
