# Generated by Django 5.0.4 on 2024-05-23 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('theatre', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.CharField(primary_key=True, serialize=False, unique=True)),
                ('client_secret', models.CharField()),
                ('payment_method', models.CharField()),
                ('amounts', models.FloatField()),
                ('seats', models.ManyToManyField(to='theatre.place')),
            ],
        ),
    ]
